# Generated by Django 3.2.6 on 2021-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtor_nome', models.CharField(help_text='Nome do produtor rural', max_length=50)),
                ('produtor_email', models.EmailField(help_text='E-mail do produtor', max_length=254)),
                ('produtor_cpf', models.CharField(max_length=20, verbose_name='CPF do produtor rural')),
                ('produtor_data_colheita', models.DateField(blank=True, null=True, verbose_name='Data da colheita do produtor')),
            ],
        ),
    ]
