# Generated by Django 3.2.6 on 2021-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isencao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perda',
            name='lavoura',
            field=models.CharField(choices=[('milho', 'milho'), ('soja', 'soja'), ('trigo', 'trigo'), ('feijao', 'feijão'), ('outro', 'outro')], max_length=30, null=True),
        ),
    ]
