# Generated by Django 3.2.6 on 2021-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isencao', '0003_alter_perda_produtor_data_colheita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perda',
            name='produtor_data_colheita',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
